busara_recruit/urls.py
from django.conf.urls import include,url
from django.contrib import admin
#import home

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin/', admin.site.urls),
	url(r'^employers/', include('employers.urls')),
	url(r'^jobs/', include('jobs.urls')),
	url(r'^candidates/', include('employees.urls')),
	url(r'^interviews/', include('interviews.urls')),
	url(r'^summernote/', include('django_summernote.urls')),
]

employers/urls.py
from django.conf.urls import url

from . import views
app_name = 'employers' #namespacing prevents conflicts when there are multiples views with same name in different apps

urlpatterns = [
    # url(r'^$', views.index),
	url(r'^dashboard/$', views.dashboard, name="dashboard"),
	url(r'^login/$', views.login_employer, name="login"),
	url(r'^logout/$', views.logout_employer, name="logout"),
    url(r'^register/$', views.register, name="register"),
	url(r'^email_confirmation/(?P<email>\w+|[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})$', views.email_confirmation, name="email_confirmation"),
	

]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.home),
    url(r'^home/$', views.home, name="home"),

    # url(r'^(?P<question_id>[0-9]+)/$', views.apply_job, name='applyjob'),

]

jobs/urls.py
from django.conf.urls import url

from . import views

app_name = 'jobs'  # namespacing prevents conflicts when there are multiples views with same name in different apps

urlpatterns = [
    url(r'^$', views.all_jobs),
    url(r'^create/$', views.create_job, name="create"),
    url(r'^view/$', views.my_jobs, name="view"),
    url(r'^job_listing/$', views.all_jobs, name="job_listing"),
    url(r'^apply/(?P<job_id>[0-9]+)$', views.apply_job, name="apply"),
    url(r'^detail/(?P<job_id>[0-9]+)$', views.job_detail, name="detail"),

]

home/models.py
from django.db import models

# Create your models here.

jobs/models.py
from django.db import models

from employers.models import Employer


# Create your models here.
class Job(models.Model):
    INDUSTRIES = (
        ('Any', 'Any'),
        ('Accounting', 'Accounting'),
        ('Customer Service', 'Customer Service'),
        ('Government', 'Government'),
        ('Education', 'Education'),
        ('Engineering', 'Engineering'),
        ('Hospitality', 'Hospitality'),
        ('Healthcare', 'Healthcare'),
        ('Farming and Agriculture', 'Farming and Agriculture'),
        ('IT and Telecoms', 'IT and Telecoms'),
        ('Legal', 'Legal'),
        ('Security', 'Security'),
        ('Other', 'Other'),
    )
    AVAILABILITY = (
        ('Fulltime', 'Fulltime'),
        ('Part time', 'Part time'),
    )
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE)
    title = models.CharField(blank=False, max_length=80, default='')
    description = models.CharField(max_length=500, blank=False, default='')
    requirements = models.CharField(max_length=12000, default='')  # large max_length to accomodate storage of html text
    benefits = models.CharField(max_length=200, null=True, blank=True)
    industry = models.CharField(max_length=30, choices=INDUSTRIES, default=INDUSTRIES[0][0])
    availability = models.CharField(max_length=30, choices=AVAILABILITY, default=AVAILABILITY[0][0])
    location = models.CharField(max_length=100, default='')
    created_on = models.DateTimeField(auto_now=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.title

jobs/forms.py
from django import forms
from django.forms import ModelForm, Textarea, TextInput
from django_summernote.widgets import SummernoteWidget

from jobs.models import Job


class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = ['title', 'industry', 'location', 'availability', 'description', 'requirements', 'benefits']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control', 'placeholder': "Job Title"}),
            'industry': forms.Select(attrs={'class': 'form-control'}),
            'location': TextInput(attrs={'class': 'form-control', 'placeholder': "Region, city or zip code"}),
            'availability': forms.Select(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control', 'cols': 2, 'rows': 5,
                                           'placeholder': "Enter the job description here; include key areas of responsibility and what the candidate might do on a typical day"}),
            'requirements': SummernoteWidget(attrs={'class': 'form-control',
                                                    'placeholder': "Enter job requirements here; from the soft skills to the specific skills needed to run the job"}),
            'benefits': Textarea(attrs={'class': 'form-control', 'cols': 4, 'rows': 5,
                                        'placeholder': "Enter the perks that an employee may be entitled to"}),
        }

home/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404
from employees.forms import EmployeeForm
from jobs.models import Job
import logging


# Get an instance of a logger
logger = logging.getLogger(__name__)

# Create your views here.
def home(request):
    return render(request,'home/index.html')
	

	
	

jobs/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from employees.forms import EmployeeForm
from jobs.models import Job
from notifications.models import Notification
from .forms import JobForm


# Create your views here.
def create_job(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        job_form = JobForm(request.POST)
        # check whether it's valid:
        if job_form.is_valid():
            # Create, but don't save the new job instance.
            new_job = job_form.save(commit=False)

            # Get current user
            user = request.user

            employer_name = user.employer.company_name

            # Add employer.
            new_job.employer = user.employer
            # Save the new instance.
            new_job.save()
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('jobs:view'))

    # if a GET (or any other method) we'll create a blank form
    else:
        job_form = JobForm()

    user = request.user

    employer_name = user.employer.company_name

    return render(request, 'jobs/create_jobs.html', {'form': job_form, 'company_name': employer_name})


def my_jobs(request):
    user = request.user
    employer = user.employer

    # Get all jobs created by the current user
    jobs_list = Job.objects.filter(employer=employer).order_by('-created_on')
    return render(request, 'jobs/view_jobs.html', {'my_jobs': jobs_list, 'company_name': employer.company_name})


def all_jobs(request):
    jobs_list = Job.objects.all()
    return render(request, 'jobs/jobs.html', {'jobs_list': jobs_list})


def apply_job(request, job_id):
    # if this is a POST request we need to process the form data
    job = get_object_or_404(Job, pk=job_id)

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        employee_form = EmployeeForm(request.POST, request.FILES)
        # check whether it's valid:
        if employee_form.is_valid():
            new_employee = employee_form.save(commit=False)
            new_employee.job = job
            # new_employee.resume = request.FILES['resume']

            new_employee.save()

            # send email to employee
            new_employee.send_job_application_email(new_employee)

            # notify employer of new application
            message = new_employee.first_name + " has applied for " + job.title
            Notification.objects.create(message=message, employer=job.employer)

            # redirect to a new URL:
            return render(request, 'jobs/application_successful.html',
                          {'company_name': job.employer.company_name, "job_position": job.title})

    # if a GET (or any other method) we'll create a blank form
    else:
        employee_form = EmployeeForm()

    return render(request, 'jobs/apply_job.html', {'form': employee_form, 'job': job})


def job_detail(request, job_id):
    # if this is a POST request we need to process the form data
    job = get_object_or_404(Job, pk=job_id)

    return render(request, 'jobs/job_details.html', {'job_item': job})

home/templates/home/application_successful.html
<!DOCTYPE html>
<html>
  <head>
    <title>Job Application</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8" />

	{% load static %}
    <link rel="icon" type="image/ico" href="{% static 'employers/images/favicon.ico' %}" />
    <!-- Bootstrap -->
    <link href="{% static 'employers/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
   
    <link rel="stylesheet" href="{% static 'employers/css/bootstrap-checkbox.css' %}">

    <link href="{% static 'employers/css/minoral.css' %}" rel="stylesheet">
	<link href="{% static 'employers/css/style.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="brownish-scheme">

    <!-- Preloader -->
    <div class="mask"><div id="loader"></div></div>
    <!--/Preloader -->

    <!-- Wrap all page content here -->
    <div id="wrap">

      


      <!-- Make page fluid -->
      <div class="row">         
        




        
        <!-- Page content -->
        <div id="content" class="col-md-12 ">
		
		
		
		  <h1>Congratulations!.</strong></h1>
          <p class="lead bold">Your job application for the {{job_position}} position has been successfuly submitted to  {{company_name}}</p>

		  <a href="{% url 'home:home'%}">Home</a>
        </div>
        <!-- Page content end -->






      </div>
      <!-- Make page fluid-->




    </div>
    <!-- Wrap all page content end -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'employers/js/bootstrap.min.js' %}"></script>
    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js?lang=css&amp;skin=sons-of-obsidian"></script>
    <script src="{% static 'employers/js/plugins/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'employers/js/plugins/blockui/jquery.blockUI.js' %}"></script>


    <script src="{% static 'employers/js/minoral.min.js' %}"></script>
	<script src="{% static 'employers/js/validateInput.js' %}"></script>

    <script>
    $(function(){
      
     //$('.welcome').addClass('animated bounceIn');

    })
      
    </script>
  </body>
</html>

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

	{% load static %}
    <title>Busara recruit</title>
	<link rel="icon" type="image/ico" href="{% static 'employers/images/favicon.ico' %}" />

	
    <!-- Bootstrap core CSS -->
    <link href="{% static 'home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'home/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'home/css/agency.min.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Busara recruit</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
		    <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'jobs:job_listing'%}">Jobs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'employers:login'%}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'employers:register'%}">Signup</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Header -->
    <header class="masthead">
      <div class="container">
        <div class="intro-text">
          <div class="intro-lead-in">Welcome To Busara recruit</div>
          <div class="intro-heading">All-in-one 
recruiting software for 
ambitious companies</div>
          <a class="btn btn-xl js-scroll-trigger" href="{% url 'employers:register'%}">Try it for free</a>
        </div>
      </div>
    </header>

    <!-- Services -->
    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Services</h2>
            <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
          </div>
        </div>
        <div class="row text-center">
          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x text-primary"></i>
              <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">Find, nurture and progress
the best talent</h4>
            <p class="text-muted">Busara recruit is more than a candidate tracking system. Build and nurture meaningful relationships with candidates over time.</p>
          </div>
          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x text-primary"></i>
              <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">Reliable and flexible</h4>
            <p class="text-muted">24/7 customer support, 
avg. response under 25 mins.</p>
          </div>
          <div class="col-md-4">
            <span class="fa-stack fa-4x">
              <i class="fa fa-circle fa-stack-2x text-primary"></i>
              <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
            </span>
            <h4 class="service-heading">Hire collaboratively</h4>
            <p class="text-muted">Create the team you need for every job. Transparent communication, 2-way email sync and an intuitive interface keeps everyone up to speed. Engage your external recruiters via Workable to keep all your candidates and prospects in one place.</p>
          </div>
        </div>
      </div>
    </section>

    



    <!-- Clients -->
    <section class="py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-3 col-sm-6">
            <a href="#">
              <img class="img-fluid d-block mx-auto" src="{% static 'home/img/logos/envato.jpg' %}" alt="">
            </a>
          </div>
          <div class="col-md-3 col-sm-6">
            <a href="#">
              <img class="img-fluid d-block mx-auto" src="{% static 'home/img/logos/designmodo.jpg' %}" alt="">
            </a>
          </div>
          <div class="col-md-3 col-sm-6">
            <a href="#">
              <img class="img-fluid d-block mx-auto" src="{% static 'home/img/logos/themeforest.jpg' %}" alt="">
            </a>
          </div>
          <div class="col-md-3 col-sm-6">
            <a href="#">
              <img class="img-fluid d-block mx-auto" src="{% static 'img/logos/creative-market.jpg" alt="">
            </a>
          </div>
        </div>
      </div>
    </section>

    
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; Busara recruit 2017</span>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-linkedin"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'home/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'home/vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'home/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'home/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Contact form JavaScript -->
    <script src="{% static 'home/js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'home/js/contact_me.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'home/js/agency.min.js' %}"></script>

  </body>

</html>

home/templates/home/jobs.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

	{% load static %}
    <title>Jobs | Busara recruit</title>

   
	
	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'home/css/agency.min.css' %}" rel="stylesheet">
	<link href="{% static 'home/css/main.css' %}" rel="stylesheet">
	

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav style="background:black"class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Busara recruit</a>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'home:home'%}">Home</a>
            </li>
           
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'employers:login'%}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'employers:register'%}">Sign up</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

   

	

					
					
						
							
								
    
      <div class="container">
			<div class="section latest-jobs-ads">
				<div class="section-title tab-manu">
					<h4>Latest Jobs</h4>
					
				</div>
				
				{% for job_item in jobs_list %}
						<div class="job-ad-item">
							<div class="item-info">
								<div class="item-image-box">
									<div class="item-image">
										<a href="#"><img src="{% static 'home/img/default_company_logo.jpg'%}" alt="Image" class="img-responsive"></a>
									</div><!-- item-image -->
								</div>

								<div class="ad-info">
									<span><a href="#" class="title">{{ job_item.title }}</a> @ <a href="#">{{ job_item.employer.company_name }}</a></span>
									<div class="ad-meta">
										<ul>
											<li><a href="#"><i class="fa fa-map-marker" aria-hidden="true"></i>{{ job_item.location }} </a></li>
											<li><a href="#"><i class="fa fa-clock-o" aria-hidden="true"></i>{{ job_item.availability }} </a></li>
											<li style="visibility:hidden"><a href="#"><i class="fa fa-money" aria-hidden="true"></i>$25,000 - $35,000</a></li>
											<li><a href="#"><i class="fa fa-tags" aria-hidden="true"></i>{{ job_item.industry }}</a></li>
										</ul>
									</div><!-- ad-meta -->									
								</div><!-- ad-info -->
								<div class="button">
							
									<a href="{% url 'home:apply_job' job_item.id %}" class="btn btn-primary">Apply Now</a>
								</div>
							</div><!-- item-info -->
						</div><!-- ad-item -->	
						{% endfor %}

				<div class="tab-content">
					<div role="tabpanel" class="tab-pane fade in" id="hot-jobs">
					
					

						
					
						

						

						
					</div><!-- tab-pane -->

					
						


						
					</div><!-- tab-pane -->
				</div><!-- tab-content -->
			</div><!-- trending ads -->		

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; Busara recruit 2017</span>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-linkedin"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    

  <!-- Bootstrap core JavaScript -->
    <script src="{% static 'home/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'home/vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'home/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'home/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Contact form JavaScript -->
    <script src="{% static 'home/js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'home/js/contact_me.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'home/js/agency.min.js' %}"></script>

  </body>

</html>