busara_recruit/urls.py
from django.conf.urls import include,url
from django.contrib import admin
#import home

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin/', admin.site.urls),
	url(r'^employers/', include('employers.urls')),
	url(r'^jobs/', include('jobs.urls')),
	url(r'^candidates/', include('employees.urls')),
	url(r'^interviews/', include('interviews.urls')),
	url(r'^summernote/', include('django_summernote.urls')),
]

employees/urls.py
from django.conf.urls import url

from . import views
app_name = 'candidates' #namespacing prevents conflicts when there are multiples views with same name in different apps

urlpatterns = [
	url(r'^view/$', views.my_candidates, name="view"),
	url(r'^profile/(?P<id>[0-9]+)$', views.candidate_profile, name="profile"),
	url(r'^download/(?P<file_name>.+)$', views.download, name="download")
   

]

employers/urls.py
from django.conf.urls import url

from . import views
app_name = 'employers' #namespacing prevents conflicts when there are multiples views with same name in different apps

urlpatterns = [
    # url(r'^$', views.index),
	url(r'^dashboard/$', views.dashboard, name="dashboard"),
	url(r'^login/$', views.login_employer, name="login"),
	url(r'^logout/$', views.logout_employer, name="logout"),
    url(r'^register/$', views.register, name="register"),
	url(r'^email_confirmation/(?P<email>\w+|[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})$', views.email_confirmation, name="email_confirmation"),
	

]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.home),
    url(r'^home/$', views.home, name="home"),

    # url(r'^(?P<question_id>[0-9]+)/$', views.apply_job, name='applyjob'),

]

interviews/urls.py
from django.conf.urls import url

from . import views

app_name = 'interviews'  # namespacing prevents conflicts when there are multiples views with same name in different apps

urlpatterns = [
    url(r'^schedule/([0-9]+)/$', views.schedule_interview, name="schedule"),
    url(r'^view/$', views.my_interviews, name="view"),

]

jobs/urls.py
from django.conf.urls import url

from . import views

app_name = 'jobs'  # namespacing prevents conflicts when there are multiples views with same name in different apps

urlpatterns = [
    url(r'^$', views.all_jobs),
    url(r'^create/$', views.create_job, name="create"),
    url(r'^view/$', views.my_jobs, name="view"),
    url(r'^job_listing/$', views.all_jobs, name="job_listing"),
    url(r'^apply/(?P<job_id>[0-9]+)$', views.apply_job, name="apply"),
    url(r'^detail/(?P<job_id>[0-9]+)$', views.job_detail, name="detail"),

]

employees/models.py
from django.db import models
from .threads import JobApplicationThread

from jobs.models import Job


# Employee/Job Applicant/Candidate.
class Employee(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(blank=False, max_length=30, default="")
    last_name = models.CharField(blank=False, max_length=30, default="")
    email = models.EmailField(blank=False, max_length=35, default="")
    phone_number = models.CharField(blank=False, max_length=12)
    address = models.CharField(blank=True, max_length=60)
    cover_letter = models.CharField(max_length=17000, default='')  # large max_length to accomodate storage of html text
    resume = models.FileField(upload_to='resume/%Y%m%d/', default='')
    application_date = models.DateTimeField(auto_now=True)
    is_shortlisted = models.BooleanField(default=False)

    def __str__(self):  # __unicode__ on Python 2
        return self.first_name + ' ' + self.last_name

    # Send email asychronously
    def send_job_application_email(self, employee):
        email_thread = JobApplicationThread(employee)
        email_thread.start()

employees/forms.py
from django import forms
from django.forms import ModelForm, Textarea,TextInput, ClearableFileInput
from django_summernote.widgets import SummernoteWidget
from employees.models  import Employee

class EmployeeForm(ModelForm):
		class Meta:
			model = Employee
			exclude = ['job','application_date','is_shortlisted']
			widgets = {
			'first_name': TextInput(attrs={'class': 'form-control','placeholder':"First name"}),
			'last_name': TextInput(attrs={'class': 'form-control','placeholder':"Last name"}),
			'email': TextInput(attrs={'class': 'form-control','placeholder':"Email address"}),
			'phone_number': TextInput(attrs={'class': 'form-control','placeholder':"Phone number"}),
			'address': TextInput(attrs={'class': 'form-control','placeholder':"Address"}),
			'cover_letter': SummernoteWidget(attrs={'class': 'form-control','cols': 6, 'rows': 5,'placeholder':"Cover letter"}),
			'resume': ClearableFileInput(attrs={'accept': '.doc,.pdf'}),
			}
			

employees/views.py
import os

from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from employees.models import Employee
from jobs.models import Job



# Get all candidates who applied for jobs belonging to the current user
def my_candidates(request):
    user = request.user
    employer = user.employer

    jobs = Job.objects.filter(employer=employer)
    # Get all candidate who have applied for job belonging to this user
    # Order by application_date descending
    candidate_list = Employee.objects.filter(job__in=jobs).order_by('-application_date')
    return render(request, 'employees/view_candidates.html',
                  {'candidate_list': candidate_list, 'company_name': employer.company_name})



# Get candidate profile
def candidate_profile(request, id):
    user = request.user
    employer = user.employer

    profile = get_object_or_404(Employee, pk=id)
    return render(request, 'employees/view_profile.html', {'profile': profile, 'company_name': employer.company_name})


def download(request, file_name):
    file_path = os.path.join(settings.MEDIA_ROOT, file_name)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            # response = HttpResponse(fh.read(), content_type="application/pdf")
            response = HttpResponse(fh.read(), content_type="application/octet-stream")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404

employees/templates/employees/view_profile.html
<!DOCTYPE html>
<html>
  <head>
    <title>Profile</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8" />
    {% load static %}
    <link rel="icon" type="image/ico" href="{% static 'employers/images/favicon.ico' %}" />
    <!-- Bootstrap -->
    <link href="{% static 'employers/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'employers/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'employers/css/rickshaw.min.css' %}">
    <link rel="stylesheet" href="{% static 'employers/css/bootstrap-checkbox.css' %}">
    <link rel="stylesheet" href="{% static 'employers/css/chosen-bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'employers/js/plugins/tabdrop/css/tabdrop.css' %}">
    <link href="{% static 'employers/css/minoral.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="brownish-scheme">

    <!-- Preloader -->
    <div class="mask"><div id="loader"></div></div>
    <!--/Preloader -->

    <!-- Wrap all page content here -->
    <div id="wrap">

      


      <!-- Make page fluid -->
      <div class="row">
        




        <!-- Fixed navbar -->
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
          


          <!-- Branding -->
          <div class="navbar-header col-md-2">
            <a class="navbar-brand" href="index.html">
              <strong>Busara</strong> <span class="divider vertical"></span> Recruit
            </a>
            <div class="sidebar-collapse">
              <a href="index.html#">
                <i class="fa fa-bars"></i>
              </a>
            </div>
          </div>
          <!-- Branding end -->


          <!-- .nav-collapse -->
          <div class="navbar-collapse">
            

            

            <!-- Content collapsing at 768px to sidebar -->
            <div class="collapsing-content">









              <!-- User Controls -->
              <div class="user-controls">
                <ul>

                 
                  <li class="dropdown messages">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="index.html#">
                      <span class="badge badge-red" id="user-new-messages">3</span>{{company_name}}</strong> <i class="fa fa-angle-down"></i>
                    </a>
                    <div class="profile-photo">
                      <img src="images/profile-photo.jpg" alt />
                    </div>
                    <ul class="dropdown-menu wide arrow red nopadding">
                      <li><h1>You have <strong>3</strong> new messages</h1></li>

                      <li>
                        <a class="cyan" href="index.html#">
                          <div class="profile-photo">
                            <img src="images/ici-avatar.jpg" alt />
                          </div>
                          <div class="message-info">
                            <span class="sender">Ing. Imrich Kamarel</span>
                            <span class="time">12 mins</span>
                            <div class="message-content">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum</div>
                          </div>
                        </a>
                      </li>

                      

                      

                      <li>
                        <a class="orange" href="index.html#">
                          <div class="profile-photo">
                            <img src="images/george-avatar.jpg" alt />
                          </div>
                          <div class="message-info">
                            <span class="sender">George McCain</span>
                            <span class="time">6 hours</span>
                            <div class="message-content">Lorem ipsum dolor sit amet, consectetur adipisicing elit</div>
                          </div>
                        </a>
                      </li>


                      <li><a href="index.html#">Check all messages <i class="fa fa-angle-right"></i></a></li>
                    </ul>
                  </li>
				  
				   <li>
                     <a href="{% url 'employers:logout' %}"><i class="fa fa-power-off"></i></a>
                  </li>

                  

                </ul>
              </div>
              <!-- User Controls end -->

            



            </div>
            <!-- /Content collapsing at 768px to sidebar -->



            <!-- Sidebar -->
            <ul class="nav navbar-nav side-nav" id="navigation">
              <li class="collapsed-content">
                <!-- Collapsed content pasting here at 768px -->
              </li>
              <li class="user-status status-online" id="user-status">
                <div class="profile-photo">
                  <img src="{% static 'employers/images/profile-photo.jpg' %}" alt />
                </div>
                <div class="user">
                  {{company_name}}
                  
                </div>
              </li>
			  
			  <li class="dropdown">
                <a href="{% url 'employers:dashboard'%}" class="dropdown-toggle" title="Dashboard">
                  <i class="fa fa-dashboard">
                    <span class="overlay-label red"></span>
                  </i> 
                  Dashboard 
                </a>
               
              </li>
			   <li class="dropdown open">
                <a href="index.html#" class="dropdown-toggle" data-toggle="dropdown" title="Forms">
                  <i class="fa fa-list">
                    <span class="overlay-label green"></span>
                  </i>
                  Jobs <b class="fa fa-angle-left dropdown-arrow"></b>
                </a>
                <ul class="dropdown-menu">
                  <li >
                    <a href="{% url 'jobs:create'%}" title="Common Elements">
                      <i class="fa fa-thumb-tack"><span class="overlay-label green80"></span></i>
                      Create jobs
                    </a>
                  </li>
                  <li class="active">
                    <a href="{% url 'jobs:view'%}" title="Validation">
                      <i class="fa fa-check-square"><span class="overlay-label green60"></span></i>
                      View Jobs
                    </a>
                  </li>
                  <li>
                    <a href="#"  title="Form Wizard">
                      <i class="fa fa-shield"><span class="overlay-label green40"></span></i>
                      Update Jobs
                    </a>
                  </li>
                </ul>
              </li>
			  
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" title="Dashboard">
                  <i class="fa fa-dashboard">
                    <span class="overlay-label red"></span>
                  </i> 
                  Interviews <b class="fa fa-angle-left dropdown-arrow"></b>
                  
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="#" title="Overview">
                      <i class="fa fa-eye"><span class="overlay-label red80"></span></i>
                      Schedule Interviews
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'interviews:view'%}" title="Inbox">
                      <i class="fa fa-envelope"><span class="overlay-label red60"></span></i>
                      View Interviews
                    </a>
                  </li>
                </ul>
              </li>
             
			  
			  
              <li class="dropdown">
                <a href="index.html#" class="dropdown-toggle" data-toggle="dropdown" title="Interface">
                  <i class="fa fa-pencil">
                    <span class="overlay-label amethyst"></span>
                  </i>
                  Candidates <b class="fa fa-angle-left dropdown-arrow"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url 'candidates:view'%}" title="UI Elements">
                      <i class="fa fa-puzzle-piece"><span class="overlay-label amethyst80"></span></i>
                      View Candidates
                    </a>
                  </li>
                  
                </ul>
              </li>
              
			  <li>
                <a href="#" title="Charts & Graphs">
                  <i class="fa fa-bar-chart-o">
                    <span class="overlay-label dutch"></span>  
                  </i>
                  Inbox
                </a>
              </li>
              
              
              
              
              
            </ul>
            <!-- Sidebar end -->





          </div>
          <!--/.nav-collapse -->





        </div>
        <!-- Fixed navbar end -->
        




        
        <!-- Page content -->
        <div id="content" class="col-md-12">
         

          <!-- content main container -->
          <div class="main">
            

<section class="tile">
  <div class="tile-widget nopadding">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs tabdrop align-right">
      <li class="tab-title pull-left">
      </li>
    </ul>
    <!-- / Nav tabs -->
  </div>
  <div class="tile-body tab-content">

   
    
    <!-- Tab panes -->                 
    <div id="fulltext-tab" class="tab-pane fade in active">
      
      <ul class="search-results fulltext">

        <li class="search-result">
          <div class="cover">
            
            <h4><a href="#">Profile</a></h4>
			
			<p>Name : {{profile.first_name}}</p>
			<p>Email : {{profile.email}} </p>
			<p>Phone number : {{profile.first_name}}</p>
			<p>Address : {{profile.address}}</p>
			

          </div>
        </li>
		
		 <li class="search-result">
          <div class="cover">
            
            <h4><a href="#">Cover letter</a></h4>

            <p>{{profile.cover_letter|safe}}</p>

			

          </div>
        </li>
		
		
		<li class="search-result">
          <div class="cover">
            
            <h4><a href="#"></a></h4>

          
		<a style="display:none" href="{% url 'candidates:download' profile.resume.name %}">Download Resume</a>
		
		<a style="color:white" role="button" href="{% url 'candidates:download' profile.resume.name %}" class="btn btn-orange cancel">
            <i class="fa fa-download" aria-hidden="true"></i>
            <span>Download Resume</span>
        </a>
			

			
          </div>
        </li>
      
	    <li class="search-result">
          <div class="cover">
            
         
		 <a style="color:white" role="button" href="{% url 'interviews:schedule' profile.id %}" class="btn btn-greensea">
           <i class="fa fa-address-card-o" aria-hidden="true"></i>
            <span>Shortlist</span>
        </a>
			

          </div>
        </li>
        
        
      </ul>

      <div class="pagination aligned-right">
        <div class="btn-group btn-group-sm">
          <button type="button" class="btn btn-default"><i class="fa fa-angle-left"></i></button>
          <button type="button" class="btn btn-default"><i class="fa fa-angle-right"></i></button>
        </div>
      </div>

    </div>

  </div>

</section>





            



          </div>
          <!-- /content container -->






        </div>
        <!-- Page content end -->






      </div>
      <!-- Make page fluid-->




    </div>
    <!-- Wrap all page content end -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'employers/js/bootstrap.min.js' %}"></script>
    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js?lang=css&amp;skin=sons-of-obsidian"></script>

    <script src="{% static 'employers/js/plugins/jquery.nicescroll.min.js' %}"></script>

    <script src="{% static 'employers/js/plugins/blockui/jquery.blockUI.js' %}"></script>

   
    
    <script src="{% static 'employers/js/plugins/chosen/chosen.jquery.min.js' %}"></script>

    <script src="{% static 'employers/js/plugins/tabdrop/bootstrap-tabdrop.min.js' %}"></script>

   
    <script src="{% static 'employers/js/minoral.js' %}"></script>

    
   
      
    </script>
  </body>
</html>