busara_recruit/urls.py
from django.conf.urls import include,url
from django.contrib import admin
#import home

urlpatterns = [
    url(r'^', include('home.urls')),
    url(r'^admin/', admin.site.urls),
	url(r'^employers/', include('employers.urls')),
	url(r'^jobs/', include('jobs.urls')),
	url(r'^candidates/', include('employees.urls')),
	url(r'^interviews/', include('interviews.urls')),
	url(r'^summernote/', include('django_summernote.urls')),
]

employees/urls.py
from django.conf.urls import url

from . import views
app_name = 'candidates' #namespacing prevents conflicts when there are multiples views with same name in different apps

urlpatterns = [
	url(r'^view/$', views.my_candidates, name="view"),
	url(r'^profile/(?P<id>[0-9]+)$', views.candidate_profile, name="profile"),
	url(r'^download/(?P<file_name>.+)$', views.download, name="download")
   

]

employers/urls.py
from django.conf.urls import url

from . import views
app_name = 'employers' #namespacing prevents conflicts when there are multiples views with same name in different apps

urlpatterns = [
    # url(r'^$', views.index),
	url(r'^dashboard/$', views.dashboard, name="dashboard"),
	url(r'^login/$', views.login_employer, name="login"),
	url(r'^logout/$', views.logout_employer, name="logout"),
    url(r'^register/$', views.register, name="register"),
	url(r'^email_confirmation/(?P<email>\w+|[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})$', views.email_confirmation, name="email_confirmation"),
	

]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.home),
    url(r'^home/$', views.home, name="home"),

    # url(r'^(?P<question_id>[0-9]+)/$', views.apply_job, name='applyjob'),

]

interviews/urls.py
from django.conf.urls import url

from . import views

app_name = 'interviews'  # namespacing prevents conflicts when there are multiples views with same name in different apps

urlpatterns = [
    url(r'^schedule/([0-9]+)/$', views.schedule_interview, name="schedule"),
    url(r'^view/$', views.my_interviews, name="view"),

]

jobs/urls.py
from django.conf.urls import url

from . import views

app_name = 'jobs'  # namespacing prevents conflicts when there are multiples views with same name in different apps

urlpatterns = [
    url(r'^$', views.all_jobs),
    url(r'^create/$', views.create_job, name="create"),
    url(r'^view/$', views.my_jobs, name="view"),
    url(r'^job_listing/$', views.all_jobs, name="job_listing"),
    url(r'^apply/(?P<job_id>[0-9]+)$', views.apply_job, name="apply"),
    url(r'^detail/(?P<job_id>[0-9]+)$', views.job_detail, name="detail"),

]

jobs/models.py
from django.db import models

from employers.models import Employer


# Create your models here.
class Job(models.Model):
    INDUSTRIES = (
        ('Any', 'Any'),
        ('Accounting', 'Accounting'),
        ('Customer Service', 'Customer Service'),
        ('Government', 'Government'),
        ('Education', 'Education'),
        ('Engineering', 'Engineering'),
        ('Hospitality', 'Hospitality'),
        ('Healthcare', 'Healthcare'),
        ('Farming and Agriculture', 'Farming and Agriculture'),
        ('IT and Telecoms', 'IT and Telecoms'),
        ('Legal', 'Legal'),
        ('Security', 'Security'),
        ('Other', 'Other'),
    )
    AVAILABILITY = (
        ('Fulltime', 'Fulltime'),
        ('Part time', 'Part time'),
    )
    employer = models.ForeignKey(Employer, on_delete=models.CASCADE)
    title = models.CharField(blank=False, max_length=80, default='')
    description = models.CharField(max_length=500, blank=False, default='')
    requirements = models.CharField(max_length=12000, default='')  # large max_length to accomodate storage of html text
    benefits = models.CharField(max_length=200, null=True, blank=True)
    industry = models.CharField(max_length=30, choices=INDUSTRIES, default=INDUSTRIES[0][0])
    availability = models.CharField(max_length=30, choices=AVAILABILITY, default=AVAILABILITY[0][0])
    location = models.CharField(max_length=100, default='')
    created_on = models.DateTimeField(auto_now=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.title

jobs/forms.py
from django import forms
from django.forms import ModelForm, Textarea, TextInput
from django_summernote.widgets import SummernoteWidget

from jobs.models import Job


class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = ['title', 'industry', 'location', 'availability', 'description', 'requirements', 'benefits']
        widgets = {
            'title': TextInput(attrs={'class': 'form-control', 'placeholder': "Job Title"}),
            'industry': forms.Select(attrs={'class': 'form-control'}),
            'location': TextInput(attrs={'class': 'form-control', 'placeholder': "Region, city or zip code"}),
            'availability': forms.Select(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control', 'cols': 2, 'rows': 5,
                                           'placeholder': "Enter the job description here; include key areas of responsibility and what the candidate might do on a typical day"}),
            'requirements': SummernoteWidget(attrs={'class': 'form-control',
                                                    'placeholder': "Enter job requirements here; from the soft skills to the specific skills needed to run the job"}),
            'benefits': Textarea(attrs={'class': 'form-control', 'cols': 4, 'rows': 5,
                                        'placeholder': "Enter the perks that an employee may be entitled to"}),
        }

jobs/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from employees.forms import EmployeeForm
from jobs.models import Job
from notifications.models import Notification
from .forms import JobForm


# Create your views here.
def create_job(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        job_form = JobForm(request.POST)
        # check whether it's valid:
        if job_form.is_valid():
            # Create, but don't save the new job instance.
            new_job = job_form.save(commit=False)

            # Get current user
            user = request.user

            employer_name = user.employer.company_name

            # Add employer.
            new_job.employer = user.employer
            # Save the new instance.
            new_job.save()
            # redirect to a new URL:
            return HttpResponseRedirect(reverse('jobs:view'))

    # if a GET (or any other method) we'll create a blank form
    else:
        job_form = JobForm()

    user = request.user

    employer_name = user.employer.company_name

    return render(request, 'jobs/create_jobs.html', {'form': job_form, 'company_name': employer_name})


def my_jobs(request):
    user = request.user
    employer = user.employer

    # Get all jobs created by the current user
    jobs_list = Job.objects.filter(employer=employer).order_by('-created_on')
    return render(request, 'jobs/view_jobs.html', {'my_jobs': jobs_list, 'company_name': employer.company_name})


def all_jobs(request):
    jobs_list = Job.objects.all()
    return render(request, 'jobs/jobs.html', {'jobs_list': jobs_list})


def apply_job(request, job_id):
    # if this is a POST request we need to process the form data
    job = get_object_or_404(Job, pk=job_id)

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        employee_form = EmployeeForm(request.POST, request.FILES)
        # check whether it's valid:
        if employee_form.is_valid():
            new_employee = employee_form.save(commit=False)
            new_employee.job = job
            # new_employee.resume = request.FILES['resume']

            new_employee.save()

            # send email to employee
            new_employee.send_job_application_email(new_employee)

            # notify employer of new application
            message = new_employee.first_name + " has applied for " + job.title
            Notification.objects.create(message=message, employer=job.employer)

            # redirect to a new URL:
            return render(request, 'jobs/application_successful.html',
                          {'company_name': job.employer.company_name, "job_position": job.title})

    # if a GET (or any other method) we'll create a blank form
    else:
        employee_form = EmployeeForm()

    return render(request, 'jobs/apply_job.html', {'form': employee_form, 'job': job})


def job_detail(request, job_id):
    # if this is a POST request we need to process the form data
    job = get_object_or_404(Job, pk=job_id)

    return render(request, 'jobs/job_details.html', {'job_item': job})

jobs/templates/jobs/application_successful.html
<!DOCTYPE html>
<html>
  <head>
    <title>Job Application</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8" />

	{% load static %}
    <link rel="icon" type="image/ico" href="{% static 'employers/images/favicon.ico' %}" />
    <!-- Bootstrap -->
    <link href="{% static 'employers/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
   
    <link rel="stylesheet" href="{% static 'employers/css/bootstrap-checkbox.css' %}">

    <link href="{% static 'employers/css/minoral.css' %}" rel="stylesheet">
	<link href="{% static 'employers/css/style.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="brownish-scheme" style="background:#f2f2f2">

    
        <!-- Page content -->
		 <div class="container">
			<div class="panel panel-success" style="width:30%;margin:35%;border-radius:5pt">
			   <div class="panel-heading" style="color:white;background:#00b33c">Congratulations!.</div>
               <div class="panel-body">Your job application for the <strong>{{job_position}}</strong> position has been successfuly submitted to  <strong>{{company_name}}</strong></div>
				<div class="panel-footer"><a href="{% url 'home:home'%}">Home</a></div>
			</div>
			
        </div>
        <!-- Page content end -->



    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'employers/js/bootstrap.min.js' %}"></script>
    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js?lang=css&amp;skin=sons-of-obsidian"></script>
    <script src="{% static 'employers/js/plugins/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'employers/js/plugins/blockui/jquery.blockUI.js' %}"></script>


    <script src="{% static 'employers/js/minoral.min.js' %}"></script>
	<script src="{% static 'employers/js/validateInput.js' %}"></script>

    <script>
    $(function(){
      
     //$('.welcome').addClass('animated bounceIn');

    })
      
    </script>
  </body>
</html>

jobs/templates/jobs/create_jobs.html
<!DOCTYPE html>
<html>
  <head>
    <title>Create Jobs</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8" />
    {% load static %}
    <link rel="icon" type="image/ico" href="{% static 'jobs/images/favicon.ico' %}" />
    <!-- Bootstrap -->
    <link href="{% static 'jobs/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'jobs/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'jobs/css/rickshaw.min.css' %}">
    <link rel="stylesheet" href="{% static 'jobs/css/bootstrap-checkbox.css' %}">
    <link rel="stylesheet" href="{% static 'jobs/css/chosen-bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'jobs/js/plugins/tabdrop/css/tabdrop.css' %}">
    <link href="{% static 'jobs/css/minoral.css' %}" rel="stylesheet">
	<link href="{% static 'jobs/css/style.css' %}" rel="stylesheet">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="brownish-scheme">

    <!-- Preloader -->
    <div class="mask"><div id="loader"></div></div>
    <!--/Preloader -->

    <!-- Wrap all page content here -->
    <div id="wrap">

      


      <!-- Make page fluid -->
      <div class="row">
        




        <!-- Fixed navbar -->
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
          


          <!-- Branding -->
          <div class="navbar-header col-md-2">
            <a class="navbar-brand" href="index.html">
              <strong>Busara</strong> <span class="divider vertical"></span> Recruit
            </a>
            <div class="sidebar-collapse">
              <a href="index.html#">
                <i class="fa fa-bars"></i>
              </a>
            </div>
          </div>
          <!-- Branding end -->


          <!-- .nav-collapse -->
          <div class="navbar-collapse">
            

            

            <!-- Content collapsing at 768px to sidebar -->
            <div class="collapsing-content">









              <!-- User Controls -->
              <div class="user-controls">
                <ul>

                 
                  <li class="dropdown messages">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="index.html#">
                      <span class="badge badge-red" id="user-new-messages">3</span>{{company_name}}</strong> <i class="fa fa-angle-down"></i>
                    </a>
                    <div class="profile-photo">
                      <img src="{% static 'employers/images/profile_image_default.png' %}" alt />
                    </div>
                    <ul class="dropdown-menu wide arrow red nopadding">
                      <li><h1>You have <strong>3</strong> new messages</h1></li>

                      <li>
                        <a class="cyan" href="index.html#">
                          <div class="profile-photo">
                            <img src="images/ici-avatar.jpg" alt />
                          </div>
                          <div class="message-info">
                            <span class="sender">Ing. Imrich Kamarel</span>
                            <span class="time">12 mins</span>
                            <div class="message-content">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum</div>
                          </div>
                        </a>
                      </li>

                      

                      

                      <li>
                        <a class="orange" href="index.html#">
                          <div class="profile-photo">
                            <img src="images/george-avatar.jpg" alt />
                          </div>
                          <div class="message-info">
                            <span class="sender">George McCain</span>
                            <span class="time">6 hours</span>
                            <div class="message-content">Lorem ipsum dolor sit amet, consectetur adipisicing elit</div>
                          </div>
                        </a>
                      </li>


                      <li><a href="index.html#">Check all messages <i class="fa fa-angle-right"></i></a></li>
                    </ul>
                  </li>
                  <li>
                     <a href="{% url 'employers:logout' %}"><i class="fa fa-power-off"></i></a>
                  </li>
                  

                </ul>
              </div>
              <!-- User Controls end -->

            



            </div>
            <!-- /Content collapsing at 768px to sidebar -->



            <!-- Sidebar -->
            <ul class="nav navbar-nav side-nav" id="navigation">
              <li class="collapsed-content">
                <!-- Collapsed content pasting here at 768px -->
              </li>
              <li class="user-status status-online" id="user-status">
                <div class="profile-photo">
                  <img src="{% static 'jobs/images/profile-photo.jpg' %}" alt />
                </div>
                <div class="user">
                  {{company_name}}
                </div>
              </li>
			  
			  <li class="dropdown">
                <a href="{% url 'employers:dashboard'%}" class="dropdown-toggle" title="Dashboard">
                  <i class="fa fa-dashboard">
                    <span class="overlay-label red"></span>
                  </i> 
                  Dashboard 
                </a>
               
              </li>
			   <li class="dropdown open">
                <a href="index.html#" class="dropdown-toggle" data-toggle="dropdown" title="Forms">
                  <i class="fa fa-list">
                    <span class="overlay-label green"></span>
                  </i>
                  Jobs <b class="fa fa-angle-left dropdown-arrow"></b>
                </a>
                <ul class="dropdown-menu">
                  <li class="active">
                    <a href="{% url 'jobs:create'%}">
                      <i class="fa fa-thumb-tack"><span class="overlay-label green80"></span></i>
                      Create jobs
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'jobs:view'%}">
                      <i class="fa fa-check-square"><span class="overlay-label green60"></span></i>
                      View Jobs
                    </a>
                  </li>
                  <li>
                    <a href="form-wizard.html"  title="Form Wizard">
                      <i class="fa fa-shield"><span class="overlay-label green40"></span></i>
                      Update Jobs
                    </a>
                  </li>
                </ul>
              </li>
			  
              <li class="dropdown">
                <a href="index.html#" class="dropdown-toggle" data-toggle="dropdown" title="Dashboard">
                  <i class="fa fa-dashboard">
                    <span class="overlay-label red"></span>
                  </i> 
                  Interviews <b class="fa fa-angle-left dropdown-arrow"></b>
                  
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="#" title="Overview">
                      <i class="fa fa-eye"><span class="overlay-label red80"></span></i>
                      Schedule Interviews
                    </a>
                  </li>
                  <li>
                    <a href="{% url 'interviews:view'%}" title="Inbox">
                      <i class="fa fa-envelope"><span class="overlay-label red60"></span></i>
                      View Interviews
                    </a>
                  </li>
                </ul>
              </li>
             
			  
			  
              <li class="dropdown">
                <a href="index.html#" class="dropdown-toggle" data-toggle="dropdown" title="Interface">
                  <i class="fa fa-pencil">
                    <span class="overlay-label amethyst"></span>
                  </i>
                  Candidates <b class="fa fa-angle-left dropdown-arrow"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="{% url 'candidates:view'%}" title="UI Elements">
                      <i class="fa fa-puzzle-piece"><span class="overlay-label amethyst80"></span></i>
                      View Candidates
                    </a>
                  </li>
                  
                </ul>
              </li>
              
			  <li>
                <a href="charts.html" title="Charts & Graphs">
                  <i class="fa fa-bar-chart-o">
                    <span class="overlay-label dutch"></span>  
                  </i>
                  Inbox
                </a>
              </li>
              
              
              
              
              
            </ul>
            <!-- Sidebar end -->





          </div>
          <!--/.nav-collapse -->





        </div>
        <!-- Fixed navbar end -->
        




        
        <!-- Page content -->
        <div id="content" class="col-md-12">
          


          




          <!-- content main container -->
          <div class="main">
            



           


            


            

<section class="tile">

  <div class="tile-header">
    <h1><strong>Create Job</h1>
  </div>
  
  <div class="tile-body">
    
    {% if error_message %}<p class="error">{{ error_message }}</p>{% endif %}
	{% if success_message %}<p class="success">{{ success_message }}</p>{% endif %}
    <form action="{% url 'jobs:create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-greensea">Create job</button>
</form>
   

  </div>
  

</section>





            



          </div>
          <!-- /content container -->






        </div>
        <!-- Page content end -->






      </div>
      <!-- Make page fluid-->




    </div>
    <!-- Wrap all page content end -->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'jobs/js/bootstrap.min.js' %}"></script>
    <script src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js?lang=css&amp;skin=sons-of-obsidian"></script>

    <script src="{% static 'jobs/js/plugins/jquery.nicescroll.min.js' %}"></script>

    <script src="{% static 'jobs/js/plugins/blockui/jquery.blockUI.js' %}"></script>

   
    
    <script src="{% static 'jobs/js/plugins/chosen/chosen.jquery.min.js' %}"></script>

    <script src="{% static 'jobs/js/plugins/tabdrop/bootstrap-tabdrop.min.js' %}"></script>

   
    <script src="{% static 'jobs/js/minoral.js' %}"></script>

    
   
      
    </script>
  </body>
</html>

jobs/templates/jobs/job_details.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

	{% load static %}
    <title>{{job_item.title}}</title>

   
	
	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'home/css/agency.min.css' %}" rel="stylesheet">
	
  </head>

  <body id="page-top" >

    <!-- Navigation -->
    <nav style="background:black"class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Busara recruit</a>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'home:home'%}">Home</a>
            </li>
           
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'employers:login'%}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'employers:register'%}">Sign up</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
 <section id="job_details">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">{{job_item.title}}</h2>
            <h3 class="section-subheading text-muted">JOB BY <a href="{{ job_item.employer.company_website }}" target="_blank">{{job_item.employer.company_name}}</a></h3>
          </div>
        </div>
		<div class="row">
          <div class="col-md-12">
            <h3>Job Description</h4>
		<p>{{job_item.description}}</p>
		<h3  style="display:none">Responsibilities</h3>
		<p>{{job_item.requirements|safe}}</p>
		
		<hr/>
		<div class="button">
							
									<a href="{% url 'jobs:apply' job_item.id %}" class="btn btn-primary">Apply</a>
								</div>
          </div>
          
          
        </div>
</section>
   
	

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; Busara recruit 2017</span>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-linkedin"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

    

  <!-- Bootstrap core JavaScript -->
    <script src="{% static 'home/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'home/vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'home/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'home/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Contact form JavaScript -->
    <script src="{% static 'home/js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'home/js/contact_me.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'home/js/agency.min.js' %}"></script>

  </body>

</html>